(()=>{const C=window.MYTIJE_CONFIG||{};let data={insights:[],notes:[]},shown=6;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const fmt=d=>{try{return new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",year:"numeric"}).format(new Date(d+"T00:00:00"))}catch{return d||""}};
function jsonp(params={}){return new Promise((resolve,reject)=>{if(!C.API_URL){resolve({ok:true,data:{insights:[],notes:[]}});return}const cb="mytije_public_"+Date.now()+"_"+Math.random().toString(36).slice(2),s=document.createElement("script"),t=setTimeout(()=>{clean();reject(Error("Timeout"))},15000);function clean(){clearTimeout(t);delete window[cb];s.remove()}window[cb]=r=>{clean();resolve(r)};const u=new URL(C.API_URL);Object.entries({...params,callback:cb}).forEach(([k,v])=>u.searchParams.set(k,String(v??"")));s.onerror=()=>{clean();reject(Error("Gagal membaca Apps Script"))};s.src=u.toString();document.body.appendChild(s)})}
function pub(a=[]){return a.filter(x=>x.status==="published").sort((a,b)=>(b.date||"").localeCompare(a.date||""))}
function render(){const ins=pub(data.insights),notes=pub(data.notes),grid=document.getElementById("insightGrid"),list=document.getElementById("noteList");
 grid.innerHTML=ins.length?ins.slice(0,shown).map(x=>`<article class="content-card reveal visible"><div class="content-meta"><span>${esc(x.category||"Insight")}</span><span>${fmt(x.date)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.summary||x.body||"")}</p><div class="content-actions"><button data-read="${esc(x.id)}">Baca →</button><button data-share="${esc(x.id)}">Bagikan</button></div></article>`).join(""):`<div class="empty">Belum ada insight yang dipublikasikan.</div>`;
 list.innerHTML=notes.length?notes.slice(0,8).map(x=>`<article class="note-item reveal visible"><div class="note-date">${fmt(x.date)}</div><div class="note-copy"><h3>${esc(x.title||"Catatan")}</h3><p>${esc(x.body||x.summary||"")}</p><div class="note-actions"><button data-note="${esc(x.id)}">Bagikan</button></div></div></article>`).join(""):`<div class="empty">Belum ada catatan yang dipublikasikan.</div>`;
 document.getElementById("insightMoreWrap").hidden=ins.length<=shown;
 document.querySelectorAll("[data-read]").forEach(b=>b.onclick=()=>openInsight(b.dataset.read));
 document.querySelectorAll("[data-share]").forEach(b=>b.onclick=()=>share(getInsight(b.dataset.share)));
 document.querySelectorAll("[data-note]").forEach(b=>b.onclick=()=>share(getNote(b.dataset.note)));
}
function getInsight(id){return data.insights.find(x=>String(x.id)===String(id))}function getNote(id){return data.notes.find(x=>String(x.id)===String(id))}
function openInsight(id){const x=getInsight(id);if(!x)return;const d=document.getElementById("contentDialog"),b=document.getElementById("contentBody");b.innerHTML=`${x.image?`<img class="article-img" src="${esc(x.image)}" alt="">`:""}<div class="content-meta">${esc(x.category||"Insight")} • ${fmt(x.date)}</div><h1>${esc(x.title)}</h1><div class="article-body">${esc(x.body||x.summary||"")}</div>`;d.showModal()}
async function share(x){if(!x)return;const url=C.SITE_URL||location.href,text=`${x.title||"MyTije"}\n\n${x.summary||x.body||""}`;if(navigator.share){try{return await navigator.share({title:x.title||"MyTije",text,url})}catch(e){}}await navigator.clipboard.writeText(`${text}\n\n${url}`);alert("Teks dan link disalin.")}
document.addEventListener("DOMContentLoaded",async()=>{document.querySelector(".content-x").onclick=()=>document.getElementById("contentDialog").close();document.getElementById("insightMore").onclick=()=>{shown+=6;render()};try{const j=await jsonp({action:"public"});if(j.ok)data=j.data||data}catch(e){console.warn(e)}render()})})();